### ISSUE TITLE
FileNotFoundError: Shared library with base name 'llama' not found

### ISSUE THREAD

**Issue by 0xWOLAND** [abetlen/llama-cpp-python#1475]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/abetlen/llama-cpp-python/blob/main/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/abetlen/llama-cpp-python/discussions), and have a new bug or useful enhancement to share.

# Expected Behavior
I am trying to import `llama_cpp` into a PyQt app that is compiled with Pyinstaller. I expect that I should be able to build with Pyinstaller and use `llama_cpp` in the app.
# Current Behavior
Currently, if I import anything other than `llama_cpp` (e.g. torch), Pyinstaller works perfectly. However, if I replace the import with `llama_cpp` (not even using it anywhere), Pyinstaller throws 
```
FileNotFoundError: Shared library with base name 'llama' not found
[24507] Failed to execute script 'setup' due to unhandled exception: Shared library with base name 'llama' not found
```

# Environment and Context

``` sh
OS: macOS 14.5 23F79 arm64 
Shell: zsh 5.9 
CPU: Apple M2 Max 
GPU: Apple M2 Max 
Memory: 5062MiB / 32768MiB 
```

```
g++: 
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.5.0
Thread model: posix

make: GNU Make 3.81
python: Python 3.9.19

# Python Env Requirements
PySide6==6.7.0
llama_cpp_python==0.2.64
```

# Failure Information (for bugs)

# Steps to Reproduce

Please provide detailed steps for reproducing the issue. We are not sitting in front of your screen, so the more detail the better.
1. Run main.py
```python
# main.py
from PySide6.QtWidgets import QApplication, QMainWindow, QSystemTrayIcon, QMenu
from llama_cpp import Llama
import sys
import os


class SystemTrayIcon(QMainWindow):
    def __init__(self):
        super().__init__()
        self.menu = QMenu()
        showAction = self.menu.addAction("Show")
        showAction.triggered.connect(self.show)

    def exit(self):
        sys.exit()


if __name__ == "__main__":
    app = QApplication()
    app.setQuitOnLastWindowClosed(False)
    trayIcon = SystemTrayIcon()

    app.exec()
```
2. Compile with `pyinstaller main.py --onefile`
3. Run executable `dist/main`
4. Currently getting the error `FileNotFoundError: Shared library with base name 'llama' not found`

Thank you so much for the help!

**Comment by 0xWOLAND** [comment]
It looks like #568 might be relevant here. I'm building from a virtual environment that is in the same folder as `main.py`.

**Comment by 0xWOLAND** [comment]
I tried building without using my virtual environment, same problem :/

**Comment by 0xWOLAND** [comment]
Fixed by #709

**Comment by JulienElkaim** [comment]
@0xWOLAND  what do you mean by fixed? 
I use the most recent llama_cpp lib and I still have this error message with pyinstaller.

My personal fix to make it work is to use the --add-binary option of pyinstaller and add the lib manually, like:
```shell
"/path-to-my-env-python-folder/site-packages/llama_cpp/lib/libllama.dylib:llama_cpp/lib/" 
```
