### ISSUE TITLE
PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package

### ISSUE THREAD

**Issue by dillfrescott** [abetlen/llama-cpp-python#457]
```
Traceback (most recent call last):
  File "C:\Users\micro\miniconda3\envs\test\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\micro\miniconda3\envs\test\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\miniconda3\envs\test\lib\site-packages\llama_cpp\server\__main__.py", line 29, in <module>
    from llama_cpp.server.app import create_app, Settings
  File "C:\Users\micro\miniconda3\envs\test\lib\site-packages\llama_cpp\server\app.py", line 15, in <module>
    from pydantic import BaseModel, BaseSettings, Field, create_model_from_typeddict
  File "C:\Users\micro\miniconda3\envs\test\lib\site-packages\pydantic\__init__.py", line 206, in __getattr__
    return _getattr_migration(attr_name)
  File "C:\Users\micro\miniconda3\envs\test\lib\site-packages\pydantic\_migration.py", line 279, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0.2/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.0.2/u/import-error
```

**Comment by IgnacioFDM** [comment]
Same, solved it downgrading pydantic
`pip install pydantic==1.10.11`

**Comment by dillfrescott** [comment]
Oh. Thank you for the info!

**Comment by AbhinasRegmi** [comment]
In the pydantic v2 the BaseSettings has been moved to a different package. First install pydantic-settings by
`pip install pydantic-settings`
and replace 
'from pydantic import BaseSettings`
with
'from pydantic_settings import BaseSettings`

It should work after that.

**Comment by Calandiel** [comment]
Glad to see it's nothing more complex but this really ought to be fixed on the repo

**Comment by Calandiel** [comment]
There's some additional issues related to this as far as I can tell -- `type` no longer exists on FieldInfo (seems to be called annotation now?) which makes the server fail.

**Comment by abetlen** [comment]
@dillfrescott was this on a pip install?

FastAPI recently upgraded to pydantic v2 which should be much faster however it does introduce some breaking changes. Can you try upgrading to the new `v0.1.69` version I just published?

**Comment by uogbuji** [comment]
@abetlen On v0.1.69 I got past the OP issue with `pip install -U pydantic pydantic-settings fastapi` but I'm now running into a related error:

```python-traceback
.local/venv/llmhost/lib/python3.11/site-packages/pydantic/_internal/_fields.py:126: UserWarning: Field "model_alias" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.
  warnings.warn(
/Users/uche/.local/venv/llmhost/lib/python3.11/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'schema_extra' has been renamed to 'json_schema_extra'
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/uche/.local/venv/llmhost/lib/python3.11/site-packages/llama_cpp/server/__main__.py", line 33, in <module>
    for name, field in Settings.__model_fields__.items():
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/uche/.local/venv/llmhost/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 193, in __getattr__
    raise AttributeError(item)
AttributeError: __model_fields__. Did you mean: 'model_fields'?
```

**Comment by uogbuji** [comment]
> @abetlen On v0.1.69 I got past the OP issue with `pip install -U pydantic pydantic-settings fastapi` but I'm now running into a related error:
> …
> ```
> AttributeError: __model_fields__. Did you mean: 'model_fields'?
> ```

FYI the 0.1.70 release fixed this error.

**Comment by Alberoyang** [comment]
Hi~ sames as me. 
<img width="596" alt="截屏2023-07-10 17 55 29" src="https://github.com/abetlen/llama-cpp-python/assets/39474846/f3b1c919-f360-4a4d-a9cd-414d683e414f">
I can't satisfy all.

**Comment by snxraven** [comment]
I am also seeing this issue within my docker builds, not sure how to fix it, I am seeing it on all recent versions

**Comment by snxraven** [comment]
Latest release 0.1.71 fixed this issue for me.

**Comment by larrycai** [comment]
> pip install pydantic==1.10.11

now llama_cpp_python is 0.2.11, this changes don't work

> ModuleNotFoundError: No module named 'pydantic._internal'

**Comment by rashidasgari** [comment]
I'm starting to have import errors after migration. I get: `ImportError: cannot import name 'BaseSettings' from 'pydantic_settings' (/usr/local/lib/python3.8/site-packages/pydantic_settings/__init__.py)`  I have done pip install pydantic pydantic-settings and already importing BaseSettings from pydantic_settings.

**Comment by DLesmes** [comment]
it is not resolve, why did you close it @abetlen ❓ 

despite to do this:
`pip install pydantic-settings`

and run this:
`from pydantic_settings import BaseSettings`

it doesn’t work for many libraries and it's dependencies 🐍

**Comment by Srajangpt1** [comment]
I am running into similar error

**Comment by abetlen** [comment]
@DLesmes it should be resolved with the `pydantic-settings` dependency in `pyproject.toml`. If  you run try `python3 -m pip install pydantic-settings` then `python3 -c "from pydantic_settings import BaseSettings"` does that still cause issues? It may be a mismatch between your pip and python intepreter.

**Comment by aguennoune** [comment]
`pip install pydantic==1.10.11` 
It works! `streamlit_pydantic` won't work without this `pydantic` version downgrade

**Comment by Harshad046** [comment]
> In the pydantic v2 the BaseSettings has been moved to a different package. First install pydantic-settings by `pip install pydantic-settings` and replace `from pydantic import BaseSettings` with `from pydantic_settings import BaseSettings`
> 
> It should work after that.

I used your solution but I am still getting the same message as I am trying to use pandas_profiling or streamlit_pandas_profiling, you know any fix for that ?

**Comment by medsouza** [comment]
@Harshad046, pandas_profiling has been deprecated. Use ydata_profiling instead. Uninstall everything follow the instructions in the link below:
https://github.com/ydataai/ydata-profiling

![image](https://github.com/user-attachments/assets/f716f8f0-db37-49bb-8e1b-cb965fafeb62)
